data = {
'Movie_1': 'The Shawshank Redemption',
'Movie_2': 'The Godfather',
'Movie_3': 'The Dark Knight',
'Movie_4': 'Pulp Fiction',
'Movie_5': 'Forrest Gump',
'Movie_6': 'The Matrix',
'Movie_7': 'Titanic',
'Movie_8': 'Gladiator',
'Movie_9': 'The Lion King',
'Movie_10': 'The Lord of the Rings: The Fellowship of the Ring',
'Movie_11': 'The Lord of the Rings: The Two Towers',
'Movie_12': 'The Lord of the Rings: The Return of the King',
'Movie_13': 'The Godfather: Part II',
'Movie_14': "Schindler's List",
'Movie_15': '12 Angry Men',
'Movie_16': 'Inception',
'Movie_17': 'Fight Club',
'Movie_18': 'The Green Mile',
'Movie_19': 'The Shawshank Redemption',
'Movie_20': 'The Godfather',
'Movie_21': 'The Dark Knight',
'Movie_22': 'Pulp Fiction',
'Movie_23': 'Forrest Gump',
'Movie_24': 'The Matrix',
'Movie_25': 'Titanic',
'Movie_26': 'Gladiator',
'Movie_27': 'The Lion King',
'Movie_28': 'The Lord of the Rings: The Fellowship of the Ring',
'Movie_29': 'The Lord of the Rings: The Two Towers',
'Movie_30': 'The Lord of the Rings: The Return of the King',
'Movie_31': 'The Godfather: Part II',
'Movie_32': "Schindler's List",
'Movie_33': '12 Angry Men',
'Movie_34': 'Inception',
'Movie_35': 'Fight Club',
'Movie_36': 'The Green Mile',
'Movie_37': 'The Shawshank Redemption',
'Movie_38': 'The Godfather',
'Movie_39': 'The Dark Knight',
'Movie_40': 'Pulp Fiction',
'Movie_41': 'Forrest Gump',
'Movie_42': 'The Matrix',
'Movie_43': 'Titanic',
'Movie_44': 'Gladiator',
'Movie_45': 'The Lion King',
'Movie_46': 'The Lord of the Rings: The Fellowship of the Ring',
'Movie_47': 'The Lord of the Rings: The Two Towers',
'Movie_48': 'The Lord of the Rings: The Return of the King',
'Movie_49': 'The Godfather: Part II',
'Movie_50': "Schindler's List",
'Movie_51': '12 Angry Men',
'Movie_52': 'Inception',
'Movie_53': 'Fight Club',
'Movie_54': 'The Green Mile',
'Movie_55': 'The Shawshank Redemption',
'Movie_56': 'The Godfather',
'Movie_57': 'The Dark Knight',
'Movie_58': 'Pulp Fiction',
'Movie_59': 'Forrest Gump',
'Movie_60': 'The Matrix',
'Movie_61': 'Titanic',
'Movie_62': 'Gladiator',
'Movie_63': 'The Lion King',
'Movie_64': 'The Lord of the Rings: The Fellowship of the Ring',
'Movie_65': 'The Lord of the Rings: The Two Towers',
'Movie_66': 'The Lord of the Rings: The Return of the King',
'Movie_67': 'The Godfather: Part II',
'Movie_68': "Schindler's List",
'Movie_69': '12 Angry Men',
'Movie_70': 'Inception',
'Movie_71': 'Fight Club',
'Movie_72': 'The Green Mile',
'Movie_73': 'The Shawshank Redemption',
'Movie_74': 'The Godfather',
'Movie_75': 'The Dark Knight',
'Movie_76': 'Pulp Fiction',
'Movie_77': 'Forrest Gump',
'Movie_78': 'The Matrix',
'Movie_79': 'Titanic',
'Movie_80': 'Gladiator',
'Movie_81': 'The Lion King',
'Movie_82': 'The Lord of the Rings: The Fellowship of the Ring',
'Movie_83': 'The Lord of the Rings: The Two Towers',
'Movie_84': 'The Lord of the Rings: The Return of the King',
'Movie_85': 'The Godfather: Part II',
'Movie_86': "Schindler's List",
'Movie_87': '12 Angry Men',
'Movie_88': 'Inception',
'Movie_89': 'Fight Club',
'Movie_90': 'The Green Mile',
'Movie_91': 'The Shawshank Redemption',
'Movie_92': 'The Godfather',
'Movie_93': 'The Dark Knight',
'Movie_94': 'Pulp Fiction',
'Movie_95': 'Forrest Gump',
'Movie_96': 'The Matrix',
'Movie_97': 'Titanic',
'Movie_98': 'Gladiator',
'Movie_99': 'The Lion King',
'Movie_100': 'The Lord of the Rings: The Fellowship of the Ring'
}
Stock_Price = {}
for i , j in data.items():
    Stock_Price[i] = j
print(Stock_Price['Movie_100'])
